name: SilkEnhancement
main: me.Devee1111.SilkEnhancementMain
version: 1.0
api-version: 1.13
depends: [SilkSpawners]
author: [Devee1111]
commands:
  sereload:
    aliases: [ser]
    description: reload the config.
    usage: /<command>
  sedebug:
    aliases: [sed]
    description: Enable/disable debug in config.
    usage: /<command> <level> <> = optional.
  secheck:
    aliases: [check]
    description: Checks if the aliases portion of config is working.
    usage: /<commnad>
permissions:
  se.admin:
    default: op
    children:
      se.reload: true
      se.debug: true
      se.command.check: true
  se.reload:
    default: op
    description: Access to /sereload
  se.debug:
    default: op
    description: access to /sedebug
  se.command.check:
    default: op
    description: access to /secheck