name: SilkEnhancement
main: me.Devee1111.SilkEnhancementMain
version: 1.0
api-version: 1.13
depend: [SilkSpawners, Vault]
author: [Devee1111]
commands:
  sereload:
    aliases: [ser]
    description: reload the config.
    usage: /<command>
  sedebug:
    aliases: [sed]
    description: Enable/disable debug in config.
    usage: /<command> <level> <> = optional.
  secheck:
    aliases: [check]
    description: Checks if the aliases portion of config is working.
    usage: /<commnad>
  sereset:
    aliases: [set]
    description: Removes a worlds data from the DataBase, used for world resets.
    usage: /<command>
permissions:
  se.admin:
    default: op
    children:
      se.reload: true
      se.debug: true
      se.command.check: true
      se.command.reset: true
  se.reload:
    default: op
    description: Access to /sereload
  se.debug:
    default: op
    description: access to /sedebug
  se.command.check:
    default: op
    description: access to /secheck
  se.command.reset:
    default: op
    description: access to /sereset